apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs-app
          image: nextjs-demo        # local Docker image
          imagePullPolicy: Never    # important: use local image
          ports:
            - containerPort: 3000
