apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs-app
          image: ghcr.io/rajendra-pm/nextjs-demo:latest
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ghcr-secret
